version: '3.8'

services:
  frontend:
    image: ghcr.io/quangdutran/lock-management-fe:latest
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    image: ghcr.io/quangdutran/lock-management-be:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

x-credentials:
  github:
    username: ${GITHUB_USERNAME}
    token: ${GITHUB_TOKEN}